### ISSUE TITLE
Fix docstrings

### ISSUE THREAD

**Issue by Adman** [fmfi-svt/candle-ng#3]
* Fix docstrings like this one https://github.com/fmfi-svt/candle-ng/blob/master/candle/timetable/Timetable.py#L5 - docstring should be put right under class definition.
* Use double quotes `"""docs"""`
* Fix docstrings like this one https://github.com/fmfi-svt/candle-ng/blob/master/candle/timetable/Timetable.py#L18 - put them under the class variable
* **DO NOT** use Slovglish - use English instead wherever possible
* Remove comments like this one https://github.com/fmfi-svt/candle-ng/blob/master/candle/timetable/Timetable.py#L128 - it's nasty

**Comment by danshaman05** [comment]
Fixed. Thanks for review @Adman!
