### ISSUE TITLE
Cosign login

### ISSUE THREAD

**Issue by Adman** [fmfi-svt/candle-ng#8]

**Comment by mrshu** [comment]
This should be relatively straightforward, provided CoSign is set up on the server where Candle is also deployed.

`ePrihlaska` works in the very same way -- all that's necessary is a wrapper around the views which are to be CoSign-covered:

https://github.com/fmfi-svt/eprihlaska/blob/41b0d961b7d183424b7e6f7c0b14b0e776a09a25/eprihlaska/views.py#L77-L85

@danshaman05 Where do you think something like this should go to in the current code structure?

**Comment by danshaman05** [comment]
> @danshaman05 Where do you think something like this should go to in the current code structure?

@mrshu authentication stuff should go to the [auth](https://github.com/fmfi-svt/candle-ng/tree/master/candle/auth) blueprint where the login & logout views are located: [candle/auth/views.py](https://github.com/fmfi-svt/candle-ng/blob/master/candle/auth/views.py)

**Comment by mrshu** [comment]
Thanks @danshaman05, let me put a quick PR together and then figure out how to deploy this somewhere where we could test it out with CoSign as well
